# Generated by Django 4.1.7 on 2023-03-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "business_name",
                    models.TextField(blank=True, max_length=30, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, max_length=11, null=True)),
                (
                    "business_phone",
                    models.TextField(blank=True, max_length=11, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.TextField(max_length=50)),
                ("product_shot_des", models.TextField(max_length=100)),
                ("product_description", models.TextField(max_length=2000)),
                ("product_price", models.FloatField()),
                ("product_discount_price", models.FloatField(blank=True, null=True)),
                ("product_img", models.FileField(upload_to="")),
                ("product_sell_price", models.FloatField()),
                ("product_stock", models.IntegerField()),
                (
                    "product_type",
                    models.TextField(
                        choices=[
                            ("Cat", "Cat"),
                            ("Dog", "Dog"),
                            ("Bird", "Bird"),
                            ("Fish", "Fish"),
                        ]
                    ),
                ),
                (
                    "product_Catecory",
                    models.TextField(
                        choices=[
                            ("Food", "Food"),
                            ("Clothes", "Clothes"),
                            ("accessories", "accessories"),
                            ("Medicine", "Medicine"),
                            ("Toys", "Food"),
                            ("Cages", "Cages"),
                        ]
                    ),
                ),
                ("discount", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_img", models.FileField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petapp.product",
                    ),
                ),
            ],
            options={"verbose_name": "Photo", "verbose_name_plural": "Photos",},
        ),
    ]
