# Generated by Django 4.1.1 on 2023-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvent',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
