# Generated by Django 4.1.1 on 2023-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_doctorvent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvent',
            name='slug',
            field=models.SlugField(default='zkzk', max_length=100),
            preserve_default=False,
        ),
    ]
