# Generated by Django 4.1.1 on 2023-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_bookedsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vent_photo',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='decive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Catecory',
            field=models.TextField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('accessories', 'accessories'), ('Medicine', 'Medicine'), ('Toys', 'Toys'), ('Cages', 'Cages'), ('none', 'none')]),
        ),
    ]
