# Generated by Django 4.1.1 on 2023-06-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_alter_vent_photo_options_profile_decive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='decive',
            new_name='device',
        ),
    ]
